version: 2.1


orbs:
  gradle: circleci/gradle@3.0.0


app_src_directory: ~/backend

workflows:
  checkout-build-test:
    jobs:
      - gradle/test:
          app_src_directory: ~/project/backend
          test_results_path: ~/project/backend/build/test-results