version: 2.1
orbs:
  gradle: circleci/gradle@3.0.0

jobs:
  parallel_tests:
    working_directory: ~/project/backend
    executor: &java8
      name: gradle/default
      tag: "8.0"
    parallelism: 5
    steps:
      - checkout:
          path: ..
      - gradle/with_cache:
          steps:
            # allows "rerun failed tests"; https://circleci.com/docs/rerun-failed-tests/
            - run:
                name: Parse classnames and split by timing
                command: |
                  cd src/test/java
                  circleci tests glob "**/*.java" | cut -c 1- | sed 's@/@.@g' | sed 's/.\{5\}$//' | circleci tests run --command=">classnames.txt xargs echo" --verbose --split-by=timings --timings-type=classname
                  [ -s classnames.txt ] || circleci-agent step halt
            - run:
                name: Run split tests
                command: |
                  GRADLE_ARGS=$(cat src/test/java/classnames.txt | awk '{for (i=1; i<=NF; i++) print "--tests",$i}')
                  echo "Prepared arguments for Gradle: $GRADLE_ARGS"
                  ./gradlew test $GRADLE_ARGS
      - store_test_results:
          path: build/test-results/test
      - store_artifacts:
          path: build/reports/tests

  deploy:
    working_directory: ~/project/backend
    executor: *java8
    steps:
      - checkout:
          path: ..
      - add_ssh_keys:
          fingerprints:
            - "ff:6e:76:65:c5:43:f2:08:ac:93:a4:c9:b3:e7:d2:ab"
      - run: ls -la ~/.ssh
      - run: cat ~/.ssh/config
      - run:
          name: SSH check
          command: ssh -o StrictHostKeychecking=no $EC2_USER@$EC2_HOST exit
      - run:
          name: Clean-up
          command: |
            ssh $EC2_USER@$EC2_HOST 'rm $(find . -name ".env.*" | xargs)' 
            ssh $EC2_USER@$EC2_HOST 'rm $(find . -name "*.jar" | xargs)'
      - run:
          name: Check clean-up
          command: ssh $EC2_USER@$EC2_HOST "ls -la"
      - gradle/with_cache:
          steps:
            - run:
                name: Build jar
                command: ./gradlew bootJar
            - run:
                name: Upload jar
                command: scp $(find build/libs -name "*.jar") $EC2_USER@$EC2_HOST:~
      # returns filepath from the current dir!
      - run:
          name: Upload .env
          command: echo "uploading .env file from S3"
#          command: scp .env.$ENV_NAME $EC2_USER@$EC2_HOST:~
      - run:
          name: List directory
          command: ssh $EC2_USER@$EC2_HOST "ls -la"
      - run:
          name: Check environment variables
          command: ssh $EC2_USER@$EC2_HOST 'export $(grep -v ^# .env.* | xargs) && echo $DB_URL'
      - run:
          name: Execute jar
          command: ssh $EC2_USER@$EC2_HOST 'export $(grep -v ^# .env.* | xargs) && nohup java -jar *.jar &' & sleep 15

workflows:
  build_and_test:
    jobs:
      - gradle/run:
          name: build
          executor:
            <<: *java8
          app_src_directory: backend
          command: build -x test -x checkstyleMain -x checkstyleTest -x jacocoTestCoverageVerification
      - parallel_tests:
          requires:
            - build
      - gradle/test:
          name: checkstyle
          requires:
            - build
          executor:
            <<: *java8
          app_src_directory: backend
          test_command: checkstyleMain; ./gradlew checkstyleTest
          reports_path: backend/build/reports/checkstyle
      - gradle/test:
          name: coverage
          requires:
            - build
          executor:
            <<: *java8
          test_command: jacocoTestReport && ./gradlew jacocoTestCoverageVerification
          app_src_directory: backend
          reports_path: backend/build/jacoco
      - deploy:
          name: Deploy to development environment
          requires:
            - build # change to `test`
          filters:
            branches:
              ignore:
                - develop
                - main
          context:
            - committed-todo-aws-ec2-dev
      - deploy:
          name: Deploy to staging environment
          requires:
            - build # change to `test`
          filters:
            branches:
              only:
                - develop
          context:
            - committed-todo-aws-ec2-staging
