version: 2.1
jobs:
  build:
    docker:
      - image: alpine:3.15
    steps:
      - run:
          name: The First Matej's Step
          command: |
            echo 'Hello Matej!'
            echo 'You are the best :-D'