version: 2.1

app_src_directory: backend/src

orbs:
  gradle: circleci/gradle@3.0.0


workflows:
  checkout-build-test:
    jobs:
      - gradle/test:
          app_src_directory: project/backend
          test_command: myTests
          test_results_path: build/test-results/